name: Postman API Test

on:
  push

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Node.js enviromment
        uses: actions/setup-node@v4.2.0
        with:
          node-version: 20

      - name: Check versions of Newman and Node
        run: |
            newman --version
            node --version
            
      - name: Install Newman-Reporter-HtmlExtra
        run: sudo npm install -g newman-reporter-htmlextra

      - name: Execute collection
        run: newman run Excluir\ Cadastro\ de\ Usu√°rio\ -\ PBI\ 20521.postman_collection.json Login\ -\ PBI\ 20518.postman_collection.json -e Dev-ronbugado.postman_environment.json -r --delay-request 1 --reporters cli,htmlextra --reporter-htmlextra-export report.html


      - name: Archive production artifacts
        if: ${{ always() }}
        uses: actions/upload-artifact@v4
        with:
          name: Report API
          path: report.html
